### ISSUE TITLE
 parameterMystery2X 

### ISSUE THREAD

**Issue by asialarocca** [dii-programmazione-avanzata/forum#1]
Salve prof, avrei un dubbio sull'output di questo esercizio: perché s3 non viene modificato nella seconda chiamata della funzione nonostante ci sia un passaggio per riferimento, mentre viene modificato il puntatore s4 che punta a s3?

**Comment by andreadelprete** [comment]
Lascio qui il link all'esercizio per comodità: https://codestepbystep.com/problem/view/cpp/pointers/parameterMystery2X

`s3` non viene modificato perchè `s4` non è un puntatore a `s3`. Penso che la confusione venga da questa riga:
```
string *s4 = new string(s3)
```
`string` è un tipo di dato, come se fosse `int` o `double`. Questa istruzione quindi crea una nuova variabile di tipo `string` usando l'allocazione dinamica. Se invece volessimo creare un puntatore `s4` alla variabile `s3` dovremmo scrivere:
```
string *s4 = &s3;
```
Spero che ora sia più chiaro.

**Comment by asialarocca** [comment]
grazie mille, adesso è più chiaro
