### ISSUE TITLE
esercizio filtri FIR

### ISSUE THREAD

**Issue by nicolosh** [dii-programmazione-avanzata/forum#3]

**Comment by nicolosh** [comment]
Sto svolgendo l'es. sui filtri FIR ma non riesco a capire 'ultimi k ingressi': potrebbe fare un esempio numerico gentilmente?

**Comment by andreadelprete** [comment]
Certo. Supponiamo che il vettore di elementi da filtrare sia
```
{3, 1, 5, 4, 6, 7, 2, 4}
```
e che la dimensione della finestra sia 3. Il risultato deve essere
```
{(3+1)/2, (3+1+5)/3, (1+5+4)/3, (5+4+6)/3, (4+6+7)/3, (6+7+2)/3, (7+2+4)/3, (2+4)/2}
```
Come puoi vedere, per il primo e l'ultimo elemento, dato che non sono disponibili tutti gli elementi della finestra, prendo soltanto quelli disponibili, e quindi divido per 2 invece che per 3.

**Comment by nicolosh** [comment]
Grazie perfetto. Avevo bisogno In realtà dell’esercizio FILTER FIR del pdf
non dell’assignment  per il 2 aprile.

**Comment by andreadelprete** [comment]
Ok, avevo frainteso. Per quanto riguarda quegli esercizi, la consegna è appositamente vaga, quindi sta a voi decidere come fare. Dato che non ci sono test specifici da passare, ogni soluzione ragionevole è accettabile. Io nella mia soluzione ad esempio ho deciso di utilizzare il primo elemento in sostituzione degli elementi mancanti, il che equivale ad assumere che il segnale fosse stazionario prima della sequenza data.

**Comment by nicolosh** [comment]
Ho capito per la accettabilità della soluzione ma l’es in se’ poco

Il giorno ven 27 mar 2020 alle 21:11 Andrea Del Prete <
notifications@github.com> ha scritto:

**Comment by andreadelprete** [comment]
Il problema si pone soltanto per i primi elementi, dato che non si hanno abbastanza elementi precedenti. Io ho quindi supposto che gli elementi precedenti il primo (che non sono disponibili nei dati) fossero tutti uguali al primo. Se quindi supponiamo di avere gli elementi da filtrare nell'array `x`, ed i coefficienti del filtro nell'array `a`, che contiene 3 elementi. Gli elementi in uscita `y` dovranno essere:
```
y[0] = a[0]*x[0] + a[1]*x[0] + a[2]*x[0]
y[1] = a[0]*x[1] + a[1]*x[0] + a[2]*x[0]
y[2] = a[0]*x[2] + a[1]*x[1] + a[2]*x[0]
y[3] = a[0]*x[3] + a[1]*x[2] + a[2]*x[1]
```
Ora è più chiaro?

**Comment by andreadelprete** [comment]
@nicolosh se il dubbio è stato chiarito ti chiederei di chiudere questa issue con il pulsante qui sotto. Grazie, Andrea.

**Comment by nicolosh** [comment]
Va bene, ora è più chiaro.
 Cordialmente N. Cavalieri

Il giorno ven 27 mar 2020 alle 21:40 Andrea Del Prete <
notifications@github.com> ha scritto:
