### ISSUE TITLE
Funzione Multiply del compito

### ISSUE THREAD

**Issue by Fede-Oa** [dii-programmazione-avanzata/forum#4]
Sto testando la mia funzione _multiply_ in modo "manuale" creando nel main di un progetto separato le condizioni del test_mimo assieme ad altre prove inventate e i risultati tornano.
Il problema è che quando eseguo il test_mimo.cc mi da ogni volta un errore diverso.

La mia soluzione:

```
double * multiply(const double A[], double b[], const int r, const int c)
{
    double *ris = new double[r];                            
    for (int i = 0; i < r; i++) {
        for (int j = 0; j < c; j++)
        {
            ris[i] += A[j+(c*i)] * b[j];
        }
    }
    return ris;
}
```

Errori risultanti da due run senza modificare il codice:
```
 REQUIRE(bb[i] == Approx(b[i]).epsilon(tol))
with expansion:
  -0.0 == Approx( 0.0 )
```

```
REQUIRE(bb[i] == Approx(b[i]).epsilon(tol))
with expansion:
  26815615859885194199148049996411692254958731641184786755447122887443528060147093953603748596333806855380063716372972101707507765623893139892867298012168192.0
==
Approx( 0.0 )
```
Sto forse sbagliando qualcosa nell'allocazione dell'array?

**Comment by andreadelprete** [comment]
Il codice contiene un errore, ma si tratta di uno di quegli errori che rende il comportamento del codice imprevedibile, quindi a volte potrebbe funzionare, mentre altre no. Bisogna sempre ricordarsi che alla creazione, gli array non sono inizializzati. Spero che questo possa bastare. In futuro sarebbe meglio non pubblicare la propria soluzione su questo forum, che è pubblico, e quindi tutti gli altri studenti la possono vedere. Potete usare delle email in questo caso, oppure aprire un issue sulla vostra repository privata dell'assignment.

**Comment by Fede-Oa** [comment]
Giusto, non avevo proprio considerato questa cosa. 
Grazie mille.

In futuro se dovessi fare domande specifiche sul mio codice userò la repository privata, mi scusi.

**Comment by andreadelprete** [comment]
Nessun problema!
