### ISSUE TITLE
Uso di filter in simulate_closed_loop

### ISSUE THREAD

**Issue by asialarocca** [dii-programmazione-avanzata/forum#5]
Salve prof, volevo chiederle dove dovremmo mettere la funzione `filter` nella logica di controllo ad anello chiuso. Il filtro va fatto sui dati in output della funzione `simulate_closed_loop` oppure sui dati che prende in ingresso la funzione `pi_control`?

(Abbiamo anche aggiunto una funzione `integral` che calcola l'integrale di x[n+1] da dare in ingresso alla funzione `pi_control`)

Le allego l'immagine della logica di controllo per essere più chiari.

![photo_2020-03-28_10-51-19](https://user-images.githubusercontent.com/61497331/77820423-90a6ed00-70e2-11ea-8776-19093ac80493.jpg)

**Comment by andreadelprete** [comment]
La funzione `filter` non deve essere utilizzata nella simulazione ad anello chiuso.

Non ho potuto fare a meno di notare l'utilizzo della forma plurale nelle sue affermazioni, come "Abbiamo anche aggiunto una funzione integral". Le ricordo che il conpito deve essere svolto **INDIVIDUALMENTE**. In caso contrario rimuoveremo dei punti dal voto finale.

**Comment by asialarocca** [comment]
Si si ovviamente va fatto individualmente, mi sono espressa male, ho usato il plurale e l'ho pubblicato su questo forum solo perché erano dubbi che hanno avuto anche altre persone

**Comment by andreadelprete** [comment]
Ok, perfetto allora.

**Comment by andreadelprete** [comment]
Se la mia risposta è stata chiara puoi chiudere questa issue usando il tasto qui sotto.

**Comment by asialarocca** [comment]
Certo, grazie
