### ISSUE TITLE
Ordine parametri funzione

### ISSUE THREAD

**Issue by rachelemenegoli** [dii-programmazione-avanzata/forum#6]
Volevo chiederle se è possibile spostare l'ordine di alcune variabili che ci ha dato come ingresso alle funzioni, in modo da poter dare direttamente i valori di default. In particolare se è possibile spostare `dt` della funzione `simulate_closed_loop` come ultimo parametro in ingresso così da poterlo inizializzare a 0.1.

**Comment by andreadelprete** [comment]
Se cambiaste l'ordine delle variabili i test non funzionerebbero più.
Per `simulate_closed_loop` non è necessario il valore di default di dt.

**Comment by rachelemenegoli** [comment]
va bene, grazie
